# Generated by Django 5.0.6 on 2026-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PumpManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=100)),
                ('seriesName', models.CharField(max_length=100)),
                ('modelName', models.CharField(blank=True, max_length=100)),
                ('pdfFile', models.FileField(upload_to='pdfs/')),
                ('partsJson', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PumpManual',
            },
        ),
    ]
