# Generated by Django 5.0.6 on 2026-01-11 03:16

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpmanual',
            name='pdfFile',
            field=models.FileField(upload_to=products.models.pump_pdf_path),
        ),
    ]
