# Generated by Django 5.0.6 on 2026-01-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_pumpmanual_pdffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumpmanual',
            old_name='brandName',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='pumpmanual',
            old_name='seriesName',
            new_name='productSeries',
        ),
        migrations.RemoveField(
            model_name='pumpmanual',
            name='partsJson',
        ),
    ]
