# Generated by Django 5.0.6 on 2026-01-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_brandname_pumpmanual_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeldescriptionChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productSeries', models.CharField(max_length=100)),
                ('modelSeries', models.TextField(blank=True, null=True)),
                ('center_body_material', models.TextField(blank=True, null=True)),
                ('fluid_connection', models.TextField(blank=True, null=True)),
                ('fluid_caps_manifold_material', models.TextField(blank=True, null=True)),
                ('hardware_material', models.TextField(blank=True, null=True)),
                ('seat_spacer_material', models.TextField(blank=True, null=True)),
                ('check_material', models.TextField(blank=True, null=True)),
                ('specialty_code1', models.TextField(blank=True, null=True)),
                ('specialty_code2', models.TextField(blank=True, null=True)),
                ('special_testing', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ModeldescriptionChart',
            },
        ),
    ]
