# Generated by Django 5.0.6 on 2026-01-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_modeldescriptionchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productSeries', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('partNo', models.CharField(blank=True, max_length=15, null=True)),
                ('material', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'CommonParts',
            },
        ),
    ]
